### ISSUE TITLE
README.md에서 command 수정 요청

### ISSUE THREAD

**Issue by namuuCY** [changeuikim/spring-boot-cicd-pipeline#1]
안녕하세요! ASAC에서 공부하고 있는 학생입니다.
Github Action을 통한 CI CD 파이프라인 구축을 하는데 
README.md 에 설명된 SSH 재시작 부분에서

`sudo systemctl sshd restart`가
`sudo systemctl restart sshd`로 바뀌어야 합니다.

**Comment by chang2kim** [comment]
이슈 등록 감사합니다! README의 명령어 수정하도록 하겠습니다

**Comment by namuuCY** [comment]
수정해주셔서 감사합니다.
여쭤보고 싶은 게 있는데 실례가 안된다면 이메일이나 연락 수단을 알 수 있을까요?

**Comment by chang2kim** [comment]
> 수정해주셔서 감사합니다. 여쭤보고 싶은 게 있는데 실례가 안된다면 이메일이나 연락 수단을 알 수 있을까요?
@namuuCY  https://www.instagram.com/changeui_kim/ 으로 연락주시면 됩니다!
